id: P010535
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18673
  title: ལེགས་འགྲུབ་ཡོང་བ་ཇི་ལྟར་བྱེད།
  author: ''
  volumes:
    25650af345604d29b01c87e9fbc28bc8:
      image_group_id: I8LS18675
      title: ''
      volume_number: 1
      total_pages: 189
      base_file: v001.txt
